#!/usr/bin/env escript
%%! -pa ./ebin/ -Wall

% https://stackoverflow.com/questions/20862186/how-do-i-use-external-libraries-in-an-erlang-escript

% http://erlang.org/pipermail/erlang-questions/2017-August/093012.html
-mode(compile).

main([Pattern]) ->
    Regex = pattern:to_regex(Pattern),
    main_loop:read_lines(Regex);
main(_) ->
    usage().

usage() ->
    io:format("Usage: program [PATTERN] ...\n"),
    io:format("\n"),
    io:format("       where PATTERN consists of text literals and\n"),
    io:format("       zero or more token capture sequences.\n"),
    halt(1).
