#!/usr/bin/env escript

main([]) ->
    case io:get_line("") of
        eof ->
            io:format("~n",[]);
        Line ->
            io:format("~p ", [Line]),
            main([])
    end;
main(_) ->
    usage().

usage() ->
    io:format("Usage: program [PATTERN] ...\n"),
    io:format("\n"),
    io:format("       where PATTERN consists of text literals and\n"),
    io:format("       zero or more token capture sequences.\n"),
    halt(1).

